[package]
name = "mosys"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"
links = "mosys"

[profile.release]
lto = true
panic = 'abort'

[dependencies]

[build-dependencies]
bindgen = "=0.31.3"
