[package]
name = "mosys"
version = "2.0.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"
links = "mosys"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
getopts = "=0.2.15"
lazy_static = "=1.0.0"

[build-dependencies]
bindgen = "=0.31.3"
